#!/bin/sh
node getIfMatch.js testAgainst2/2016-election-scripts.txt0.txt templates/list
node getIfMatch.js testAgainst2/2016-election-scripts.txt12.txt templates/list
node getIfMatch.js testAgainst2/2016-election-scripts.txt13.txt templates/list
node getIfMatch.js testAgainst2/2016-election-scripts.txt14.txt templates/list
node getIfMatch.js testAgainst2/2016-election-scripts.txt16.txt templates/list
node getIfMatch.js testAgainst2/2016-election-scripts.txt17.txt templates/list
node getIfMatch.js testAgainst2/2016-election-scripts.txt1.txt templates/list
node getIfMatch.js testAgainst2/2016-election-scripts.txt2.txt templates/list
node getIfMatch.js testAgainst2/2016-election-scripts.txt4.txt templates/list
node getIfMatch.js testAgainst2/2016-election-scripts.txt5.txt templates/list
node getIfMatch.js testAgainst2/2016-election-scripts.txt6.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt0.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt10.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt11.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt12.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt13.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt14.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt15.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt16.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt1.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt2.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt3.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt4.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt5.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt6.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt7.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt8.txt templates/list
node getIfMatch.js testAgainst2/national-politics-scripts.txt9.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt0.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt10.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt11.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt12.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt13.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt14.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt15.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt1.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt2.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt3.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt4.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt5.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt6.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt7.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt8.txt templates/list
node getIfMatch.js testAgainst2/space-science-scripts.txt9.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt0.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt10.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt11.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt1.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt2.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt3.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt4.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt5.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt6.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt7.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt8.txt templates/list
node getIfMatch.js testAgainst2/world-politics-scripts.txt9.txt templates/list
